/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kr.or.yi.food_mgm_program;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
